<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RunAnalyzers>false</RunAnalyzers>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <SonarQubeExclude>true</SonarQubeExclude>
    <WarningLevel>0</WarningLevel>
    <AnalysisLevel>none</AnalysisLevel>
    <NoWarn>NU1701,NETSDK1206</NoWarn>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

</Project>
